[workspace]
resolver = "2"
members = [
    "docstrings",
    "examples/counter",
    "forc",
    "forc-explore",
    "forc-fmt",
    "forc-gm",
    "forc-lsp",
    "forc-pkg",
    "forc-util",
    "scripts/examples-checker",
    "scripts/forc-documenter",
    "sway-core",
    "sway-fmt",
    "sway-ir",
    "sway-lsp",
    "sway-parse",
    "sway-types",
    "sway-utils",
    "test",
    "test-sig-gen-util",
]

[profile.dev.package.sway-lsp]
debug = 2
