[package]
name = "sway-lsp"
version = "0.6.0"
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"
description = "LSP server for Sway."

[dependencies]
dashmap = "5.1"
lspower = "1.5"
ropey = "1.3"
serde_json = "1.0.79"
sway-core = { version = "0.6.0", path = "../sway-core" }
sway-fmt = { version = "0.6.0", path = "../sway-fmt" }
sway-types = { version = "0.6.0", path = "../sway-types" }
sway-utils = { version = "0.6.0", path = "../sway-utils" }
tokio = { version = "1.3", features = ["io-std", "io-util", "macros", "net", "rt-multi-thread", "sync", "time"] }
