[project]
authors = ["Fuel Labs <contact@fuel.sh>"]
edition = "2021"
license = "Apache-2.0"
name = "wallet_smart_contract"
version = "0.1.0"

[dev-dependencies]
fuel-tx = "0.9"
fuels = "0.11"
fuels-abigen-macro = "0.11"
tokio = { version = "1.12", features = ["rt", "macros"] }

[[test]]
harness = true
name = "integration_tests"
path = "tests/harness.rs"
