[package]
name = "new-parser"
version = "0.0.1"
edition = "2021"
publish = false

[dependencies]
either = "*"
num-bigint = "*"
num-traits = "*"
unicode-xid = "*"
walkdir = "*"
ariadne = "*"
new-parser-macros = { path = "../new-parser-macros" }
extension-trait = "*"

